app:
  Name : "WBTech0"
  Version : "1.0.0"
  
database:
  Name : "wbtechdb"
  Host : "localhost"
  #Host : "database"
  Port : 5432
  SSLMode : "disable"
  Schema : "public"
  MaxPoolSize : 10

  
server:
  ShutdownTimeout : 20

nats_streaming:
  #URL : "nats:4222"
  URL : "localhost:4222"