app:
  Name : "WBTech0"
  Version : "1.0.0"
  
database:
  Name : "wbtechdb"
  Host : "localhost"
  Port : 5432
  SSLMode : "disable"
  Schema : "public"
  MaxPoolSize : 10

  
server:
  ShutdownTimeout : 5
  Addr : "3333"

nats_streaming:
  URL : "localhost:4222"